services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRESS_DB: myfinwallet
      POSTGRES_USER: finwallet
      POSTGRES_PASSWORD: finwallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data: